
# Generated by Django 2.2 on 2019-05-17 05:09

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_id', models.IntegerField()),
                ('recommend_id', models.IntegerField()),
                ('title', models.CharField(max_length=40)),
                ('body', DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容')),
                ('user', models.CharField(max_length=40)),
                ('views', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('url', models.CharField(max_length=2083)),
                ('position_city_id', models.IntegerField()),
                ('position_area_id', models.IntegerField()),
                ('detail_area', models.CharField(max_length=100)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('summary', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': '景点介绍',
                'verbose_name_plural': '景点介绍',
                'db_table': 'article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('img', models.ImageField(upload_to='ArticleImg/%Y/%m/%d')),
            ],
            options={
                'verbose_name': '文章图片',
                'verbose_name_plural': '文章图片',
                'db_table': 'article_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_info', models.TextField()),
                ('img', models.CharField(max_length=2083)),
                ('link_url', models.CharField(max_length=2083)),
                ('is_use', models.IntegerField()),
            ],
            options={
                'verbose_name': '幻灯片',
                'verbose_name_plural': '幻灯片',
                'db_table': 'banner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('max', models.BigIntegerField()),
                ('time1_flow', models.BigIntegerField()),
                ('time2_flow', models.BigIntegerField()),
                ('time3_flow', models.BigIntegerField()),
                ('time4_flow', models.BigIntegerField()),
                ('time5_flow', models.BigIntegerField()),
                ('time_6flow', models.BigIntegerField()),
                ('flow_img', models.ImageField(upload_to='FlowImg')),
            ],
            options={
                'verbose_name': '景点人流量',
                'verbose_name_plural': '景点人流量',
                'db_table': 'flow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_id', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('position_city_id', models.IntegerField()),
                ('position_area_id', models.IntegerField()),
                ('detail_massage', models.TextField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('detail_area', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '酒店',
                'verbose_name_plural': '酒店',
                'db_table': 'hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField()),
                ('img', models.ImageField(upload_to='HotelImg/%Y/%m/%d')),
            ],
            options={
                'verbose_name': '旅馆图片',
                'verbose_name_plural': '旅馆图片',
                'db_table': 'hotel_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField()),
                ('price', models.FloatField()),
                ('url', models.CharField(max_length=2083)),
            ],
            options={
                'verbose_name': '旅馆价格',
                'verbose_name_plural': '旅馆价格',
                'db_table': 'hotel_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=40)),
                ('news_body', DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.IntegerField()),
                ('img', models.ImageField(upload_to='NewsImg/%Y/%m/%d')),
            ],
            options={
                'verbose_name': '新闻图片',
                'verbose_name_plural': '新闻图片',
                'db_table': 'news_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=100)),
                ('province_url', models.CharField(max_length=2083)),
            ],
            options={
                'verbose_name': '省-区域',
                'verbose_name_plural': '省-区域',
                'db_table': 'position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PositionArea',
            fields=[
                ('position_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_city_id', models.IntegerField()),
                ('area', models.CharField(max_length=255)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
            options={
                'verbose_name': '区-区域',
                'verbose_name_plural': '区-区域',
                'db_table': 'position_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PositionCity',
            fields=[
                ('position_city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('position_id', models.IntegerField()),
                ('city', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': '市-区域',
                'verbose_name_plural': '市-区域',
                'db_table': 'position_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '景点类型',
                'verbose_name_plural': '景点类型',
                'db_table': 'type',
                'managed': False,
            },
        ),
    ]
